const magento24RequiredPHPExtensions = [
    'bcmath',
    'ctype',
    'curl',
    'dom',
    'fileinfo',
    'filter',
    'ftp',
    'gd',
    'hash',
    'iconv',
    'intl',
    'json',
    'libxml',
    'mbstring',
    'openssl',
    'pcre',
    'pdo_mysql',
    'simplexml',
    'soap',
    'sockets',
    'sodium',
    'tokenizer',
    'xmlwriter',
    'xsl',
    'zip',
    'zlib',
    'libxml',
    'openssl'
]

module.exports = magento24RequiredPHPExtensions
