<input type="button" name="import_button" id="tutorial_import_button" value="Import products">

<script type="text/javascript">
    (function  () {
        require(["jquery"], function($) {
            $(document).ready(function($) {
                $("#tutorial_import_button").on("click", function(e){
                    var importUrl = '<?php echo $block->getImportControllerUrl() ?>';
                    window.location.href = importUrl;
                })
            });
        });
    })();
</script>
